[package]
name = "chainthru-primitives"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
derive_builder.workspace = true
web3.workspace = true
sqlx.workspace = true
url.workspace = true
serde.workspace = true
serde-aux.workspace = true
serde_json.workspace = true
thiserror.workspace = true
secrecy.workspace = true
log.workspace = true

async-trait = "0.1.72"
