repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.3.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--all', '--']
      - id: clippy
        args: ['--', '-D', 'warnings']
      - id: cargo-check
  - repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.9
    hooks:
      - id: cargo-sort
  - repo: local
    hooks:
      - id: lint-yaml
        name: Lint - YAML
        language: system
        entry: yamllint .
        files: \.(yaml|yml)$
        require_serial: true
