apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chainthru-index.fullname" . }}
  labels:
    {{- include "chainthru-index.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chainthru-index.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chainthru-index.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chainthru-index.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHAINTHRU_NODE_URL
              value: {{ .Values.nodeUrl }}
            - name: CHAINTHRU_DATABASE_URL
              value: {{ .Values.databaseJDBC }}
            - name: CHAINTHRU_FROM_BLOCK
              value: {{ .Values.startBlock }}
            - name: CHAINTHRU_TO_BLOCK
              value: {{ .Values.endBlock }}
            - name: CHAINTHRU_INDEXER_THREADS
              value: {{ .Values.threads }}
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          # TODO
          command: ["./chainthru", "--server.disabled"]
          args: {{ .Values.additionalArguments }}
          livenessProbe:
            exec:
              command:
                - cat
                - /etc/passwd
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pgrep
                - chainthru
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
