collect = "logs"
queue_url = "redis://localhost:6379"
database_url = "postgres://postgres:password@localhost:5432/eventify"

[server]
host = "0.0.0.0"
port = 21420

[network]
    [network.eth]
    #node_url = "wss://mainnet.infura.io/ws/v3/f3ca0098ac2c41a78af15eab2c163492"
    node_url = "wss://eth.llamarpc.com"

    #[network.zksync]
    #node_url = "wss://mainnet.era.zksync.io/ws"
