on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Publish
jobs:
  crate:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_KEY }}

